### ISSUE TITLE
Can not export metrics to Otel collector from the OC agent

### ISSUE THREAD

**Issue by huikang** [open-telemetry/opentelemetry-service#231]
When I configure my Otel agent to export metrics to the the Otel collector with the following content in the agent config

```
receivers:
  opencensus:
    endpoint: 0.0.0.0:55678
    reconnection-delay: 2s
exporters:
  opencensus:
    endpoint: "otel-collector:55678"
  logging:
pipelines:
  metrics:
    receivers: [opencensus]
    exporters: [opencensus, logging]
```
the agent failed to be launched due to this error `2019/08/05 03:05:54 Cannot load configuration: metrics is a metrics pipeline but has a opencensus which does not support metrics`.

Could anyone help on this?
My ultimate goal is to have the collector collect stats from different agents, and have a prometheus backend to scrape stats from the single collector. Thanks.
