### ISSUE TITLE
Add factory and new-style config for Batch processor

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-service#52]
See addattributesprocessor for example.

**Comment by tigrannajaryan** [comment]
This is done.

**Comment by MosheElisha** [comment]
Hello,

Can you please explain why all configuration examples contain both "batch" and "batch/2"?

```
processors:
  batch:
  batch/2:
    timeout: 10s
    send_batch_size: 10000
    send_batch_max_size: 11000
```
https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/batchprocessor/testdata/config.yaml


From what I understand, in the configuration above, you define two processors - one "batch" with default configuration and one "batch/2" with some configuration but in the "pipelines" you are only using "batch/2".

Should I define "batch" or "batch/2" or both? and why please.

Thanks.
